apiVersion: batch/v1
kind: CronJob
metadata:
  name: kiss-elastic-sync-job-smoelenboek
spec:
  schedule: "*/59 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: kiss-elastic-sync
            image: ghcr.io/klantinteractie-servicesysteem/kiss-elastic-sync
            imagePullPolicy: Always
            args:
            - smoelenboek
            envFrom:
            - secretRef:
                name: kiss-secrets
            - configMapRef:
                name: kiss-config
          restartPolicy: Never