apiVersion: batch/v1
kind: CronJob
metadata:
  name: kiss-elastic-sync-job-kennisartikelen
spec:
  schedule: "*/59 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: kiss-elastic-sync
            image: ghcr.io/klantinteractie-servicesysteem/kiss-elastic-sync
            imagePullPolicy: Always
            envFrom:
            - secretRef:
                name: kiss-elastic-env
          restartPolicy: Never